apiVersion: v1
kind: Pod
metadata:
   name: afp2nfs
spec:
   containers:
   - name: afp2nfs_mount
     image: localhost/afp2nfs
     ports:
     - containerPort: 2049
       hostPort: 2049
       protocol: TCP
     securityContext:
        allowPrivilegeEscalation: false
        privileged: true
        readOnlyRootFilesystem: false
        seLinuxOptions:
           security-object:
              type: spc_t
     tty: true
     envFrom:
     - configMapRef:
         name: afp2nfs-configmap
         optional: false  
     volumeMounts:
     - mountPath: /dev/fuse
       name: dev-fuse
   dnsConfig: {}
   volumes:
   - name: dev-fuse
     hostPath:
        path: /dev/fuse
   restartPolicy: Always
status: {}
